baseURL = "https://beta.albertforfuture.de/"
languageCode = "de-DE"
title = "Albert for Future"
theme = "albertforfuture.de"
Paginate = 3
sectionPagesMenu = "main"
pluralizeListTitles = false
canonifyURLs = true

[params]
  offlineVersion = "v7"

[outputs]
  page = ["HTML"]
  home = ["HTML", "RSS"]
  section = ["HTML", "RSS"]
  taxonomyTerm = ["HTML"]
  taxonomy = ["HTML", "RSS"]
