baseURL = "https://beta.albertforfuture.de/"
languageCode = "de-DE"
title = "Albert for Future"
theme = "albertforfuture.de"
Paginate = 3
sectionPagesMenu = "main"
pluralizeListTitles = false
canonifyURLs = true

[outputs]
  page = ["HTML", "RawHTML"]
  home = ["HTML", "RSS", "RawHTML"]
  section = ["HTML", "RSS", "RawHTML"]
  taxonomyTerm = ["HTML", "RawHTML"]
  taxonomy = ["HTML", "RSS", "RawHTML"]
