baseURL = "https://beta.albertforfuture.de/"
languageCode = "de-DE"
title = "Albert for Future"
theme = "albertforfuture.de"
Paginate = 3
sectionPagesMenu = "main"
pluralizeListTitles = false
canonifyURLs = true


[outputs]
  home = ["HTML", "RSS", "RawHTML"]
  section = ["HTML", "RSS", "RawHTML"]
  taxonomy = ["HTML", "RSS", "RawHTML"]
