baseURL = "https://mohe2015.github.io/albertforfuture.de/"
languageCode = "de-DE"
title = "Albert for Future"
theme = "albertforfuture.de"
Paginate = 10
sectionPagesMenu = "main"
pluralizeListTitles = false

[params]
  offlineVersion = "v9"

[outputs]
  page = ["HTML"]
  home = ["HTML", "RSS"]
  section = ["HTML", "RSS"]
  taxonomyTerm = ["HTML"]
  taxonomy = ["HTML", "RSS"]

[module]
  [[module.mounts]]
    source = "node_modules"
    target = "assets"