[package]
name = "web-push"
version = "0.1.0"
authors = ["mohe2015 <mohe2015@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# https://github.com/pimeys/rust-web-push
[dependencies]
web-push = "0.6.0"
